name: dungeons-lobby
version: "0.1"
author: FirestarterMC staff
main: com.firestartermc.dungeons.lobby.DungeonsLobby
description: Firestarter's package of basic server utilities.
website: https://firestartermc.com/opensource
api-version: 1.16
depend: ['Kerosene']

commands:
  dungeon:
    description: The main dungeon command.
    aliases: [d]